"""F5 — the Bouncer: breaks are earned, not stolen.

Ask for a break, answer one retrieval question generated from your own notes. The
point is not to make breaks hard; it is that the price of a break is a rep of
retrieval practice, which is the single best-evidenced study technique there is. And
a break you are allowed to ask for is a break you never have to steal.
"""

from __future__ import annotations

import re

from .. import prompts
from ..providers import CallMeta, Provider
from ..schemas import Contract, Grade, Quiz

_WORD = re.compile(r"\b[\w'-]+\b")
_EXCLAMATIONS = re.compile(r"[!]+")

#: Shorter than this cannot contain a recalled mechanism, so it is graded without
#: spending a model call — and without the model's tendency to be kind about it.
MIN_ANSWER_WORDS = 4

_EVASIONS = ("i don't know", "idk", "dunno", "no idea", "skip", "just let me")


#: Below this there is not enough writing to build a retrieval question from, and
#: asking the model anyway produces something invented. Observed: an empty notes
#: string yielded a question about scientific theories versus laws to a student
#: revising thermodynamics — confidently irrelevant, which is worse than an error.
MIN_NOTES_WORDS = 12


def ask_question(
    provider: Provider,
    notes: str,
    *,
    contract: Contract | None = None,
    max_chars: int = 4000,
) -> tuple[Quiz, CallMeta]:
    """One retrieval question, from the student's notes when there are any.

    Falls back to the contracted topic rather than to nothing. A break should not be
    blocked because Heid Doon has not been shown any work yet, but the question must
    not pretend to quote notes it has never read — so the caller is told which source
    was used, and the UI says so.
    """
    has_notes = len(_WORD.findall(notes or "")) >= MIN_NOTES_WORDS

    if has_notes:
        prompt = prompts.render(prompts.BOUNCER_QUESTION, notes=notes[:max_chars])
        source = "your own notes"
    elif contract is not None and contract.task:
        prompt = prompts.render(prompts.BOUNCER_TOPIC_QUESTION, contract=contract.for_prompt())
        source = "your topic — I have not seen your notes yet"
    else:
        # Nothing to ask about at all. Say so instead of inventing a question.
        quiz = Quiz(question="", key_points=[])
        quiz._repairs.append("no notes and no task to ask about")
        return quiz, CallMeta(
            provider=provider.name, model=provider.model, latency_s=0.0, attempts=0, ok=True
        )

    raw, meta = provider.complete_json(prompt, max_tokens=350)
    quiz = Quiz.from_model(raw)
    quiz.source = source
    quiz._meta = meta.to_dict()
    meta.repairs = list(quiz._repairs)
    return quiz, meta


def grade_answer(
    provider: Provider, quiz: Quiz, answer: str, *, fast: bool = False
) -> tuple[Grade, CallMeta]:
    """Grade a recall answer, with a model-free path for the obvious cases.

    `fast` takes the key-point overlap path deliberately rather than only when the
    model is unreachable. It is the same arithmetic either way — what is lost is the
    warm, specific feedback the model writes, not the correctness of the pass or fail.
    """
    answer = (answer or "").strip()
    no_call = CallMeta(provider=provider.name, model=provider.model, latency_s=0.0, attempts=0, ok=True)

    if len(_WORD.findall(answer)) < MIN_ANSWER_WORDS or answer.lower() in _EVASIONS:
        return (
            Grade(
                passed=False,
                feedback="Have a real go first — even a rough version of the idea counts.",
            ),
            no_call,
        )

    if fast:
        grade = _overlap_grade(quiz, answer)
        grade._repairs.append("graded by key-point overlap (fast grading is on)")
        return grade, no_call

    raw, meta = provider.complete_json(
        prompts.render(
            prompts.BOUNCER_GRADE,
            question=quiz.question,
            key_points=quiz.key_points,
            answer=answer,
        ),
        max_tokens=300,
    )

    if not meta.ok:
        # The design doc's own kill rule: when grading is flaky, fall back to
        # key-point overlap. Still generated by the model, just not graded by it —
        # and a break should never hang on an API being up.
        grade = _overlap_grade(quiz, answer)
        grade._repairs.append("graded by key-point overlap (model unavailable)")
        return grade, meta

    grade = Grade.from_model(raw)
    # Same tone rule as the nudges in core/verdict.py: the product promises a voice
    # without exclamation marks, and grading is where the model most wants to cheer.
    # "Great job!" becomes "Great job." — warmth survives, the shouting does not.
    grade.feedback = _EXCLAMATIONS.sub(".", grade.feedback).strip()
    grade._meta = meta.to_dict()
    meta.repairs = list(grade._repairs)
    return grade, meta


def _overlap_grade(quiz: Quiz, answer: str) -> Grade:
    """Deterministic fallback: did they hit the key points, roughly?"""
    answer_words = {word.lower() for word in _WORD.findall(answer)}
    matched = [
        point
        for point in quiz.key_points
        if _significant_overlap({word.lower() for word in _WORD.findall(point)}, answer_words)
    ]
    needed = max(1, len(quiz.key_points) // 2)
    passed = len(matched) >= needed
    return Grade(
        passed=passed,
        feedback=(
            "That covers the main idea — ten minutes, then I will come and get you."
            if passed
            else "Close, but the core mechanism is still missing. Look it up, then take the break."
        ),
        matched_points=matched,
    )


def _significant_overlap(point_words: set[str], answer_words: set[str], threshold: float = 0.4) -> bool:
    content_words = {word for word in point_words if len(word) > 3}
    if not content_words:
        return False
    return len(content_words & answer_words) / len(content_words) >= threshold


def break_granted_line(contract: Contract, minutes: int = 10) -> str:
    """What the app says when the break is earned."""
    return f"Break earned — {minutes} minutes. I will come and get you for {contract.task or 'the next stretch'}."
